app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
from item.views import IndexView, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('home/', HomeView.as_view(), name='home'),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
    path('item/', include('item.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
  import debug_toolbar

  urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

app/item/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import ItemList, ItemDetail, ItemCreate, ItemDelete, ItemUpdate, ItemTagList

urlpatterns = [
    path('', ItemList.as_view(), name='item.list'),
    path('<int:pk>/', ItemDetail.as_view(), name='item.detail'),
    path('create/', ItemCreate.as_view(), name='item.create'),
    path('delete/<int:pk>/', ItemDelete.as_view(), name='item.delete'),
    path('del/<int:pk>/', views.delete_item, name='delete_item'),
    path('update/<int:pk>/', ItemUpdate.as_view(), name='item.update'),
    path('create_comment/<int:pk>/', views.create_comment, name='item.create_comment'),
    path('like/<int:pk>/', views.like, name='item.like'),
    path('tag/<int:pk>/', ItemTagList.as_view(), name='item.tag_list'),
]

app/item/models.py
from django.db import models
from user.models import User
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings
from django import template
from user.models import User
import uuid

register = template.Library()


def upload_directory_path(instance, filename):
    return f'item/{instance.id}/{str(uuid.uuid4())}.{filename.split(".")[-1]}'


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Item(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = ProcessedImageField(
        blank=True,
        null=True,
        upload_to=upload_directory_path,
        processors=[ResizeToFill(1500, 1000)],
        options={"quality": 80},
    )
    image_thumbnail = ImageSpecField(
        source="image", processors=[ResizeToFill(600, 400)], options={"quality": 80}
    )
    image_small = ImageSpecField(
        source="image", processors=[ResizeToFill(150, 150)], options={"quality": 80}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = models.ManyToManyField(Tag)
    likes = models.ManyToManyField(Like)

    def __str__(self):
        return f"{self.title}({self.author})"

    def getSmallImage(self):
        return (
            self.image_small.url
            if self.image
            else f"{settings.STATIC_URL}img/noimage.png"
        )

    def getThumbnailImage(self):
        return (
            self.image_thumbnail.url
            if self.image
            else f"{settings.STATIC_URL}img/noimage.png"
        )

    def get_currentuser_islike(self, user_id):
        is_like = False
        for l in self.islike:
            if l.user_id == user_id:
                is_like = True
                break
            else:
                is_like = False
        return is_like

    def get_comment_author_avatar(self):
        list = []
        limit = 2
        for n, c in enumerate(self.comments):
            list.append(c.author.getAvatar())
            if n == limit:
                break
        return list

    def save(self, *args, **kwargs):
        if self.id is None:
            uploaded_file = self.image

            self.image = None
            super().save(*args, **kwargs)

            self.image = uploaded_file
            if "force_insert" in kwargs:
                kwargs.pop("force_insert")

        super().save(*args, **kwargs)


class Comment(models.Model):
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

app/item/forms.py
from django import forms
from .models import Item, Tag
from imagekit.forms import ProcessedImageField

class CreateItemForm(forms.ModelForm):

  class Meta:
    model = Item
    fields = ['title', 'body', 'image', 'tags']

  title = forms.CharField()
  body = forms.CharField(widget=forms.Textarea)
  image = ProcessedImageField(spec_id='app:item:image', required=False)

  tags = forms.CharField(required=False)

app/item/views.py
from .forms import CreateItemForm
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.http.response import JsonResponse
from django.conf import settings
from django.db.models import Count, Prefetch, Q
from django.core.exceptions import FieldError
from .models import Item, Tag, Comment, Like

class ItemList(ListView):
  allow_empty = True
  model = Item
  template_name = 'item/list.html'
  ordering = '-created_at'
  paginate_by = 6
  values = {
    'origin': ('id', 'title', 'body', 'created_at', 'author_id', 'author_id__username', 'author_id__avatar', 'image', 'likes__user_id', 'likes__user_id__avatar'),
    'comment': ('id', 'body', 'created_at', 'item_id', 'author_id', 'author_id__username', 'author_id__avatar'),
      'like': ('id', 'created_at', 'user_id', 'user_id__avatar', 'user_id__username')
    }
  queryset = (
    Item.objects.all()
      .select_related('author')
      .prefetch_related(
        Prefetch(
          'comment_set',
          queryset=Comment.objects.all().select_related('author').order_by('-created_at').only(*values['comment']),
          to_attr='comments'
          )
        )
      .prefetch_related(
        Prefetch(
          'likes',
          queryset=Like.objects.all().select_related('user').order_by('-created_at').only(*values['like']),
          to_attr='islike'
          )
      )
      .annotate(
        Count('comment'),
        Count('likes'),
      )
      .only(*values['origin'])
  )

  def get_queryset(self):
    q = self.queryset.order_by('-created_at')
    if self.request.user.is_authenticated:
      q = q.annotate(currentuser_islike=Count('likes', filter=Q(likes__user=self.request.user)))
    if 'sort' in self.request.GET and self.request.GET.get('sort') != 'created_at':
      sort = self.request.GET.get('sort')
      try:
        q = q.annotate(sort=Count(sort)).order_by('-sort', '-created_at')
      except FieldError:
        q = q
    return q

  def get_context_data(self, **kwargs):
    return super().get_context_data(**kwargs)

class ItemDetail(DetailView):
  model = Item
  template_name = 'item/detail.html'
  values = {
    'origin': ('id', 'title', 'body', 'created_at', 'author_id', 'author_id__username', 'author_id__avatar', 'image', 'likes__user_id', 'likes__user_id__avatar'),
    'comment': ('id', 'body', 'created_at', 'item_id', 'author_id', 'author_id__username', 'author_id__avatar'),
      'like': ('id', 'created_at', 'user_id', 'user_id__avatar', 'user_id__username')
    }
  queryset = (
    Item.objects.all()
      .select_related('author')
      .prefetch_related(
        Prefetch(
          'comment_set',
          queryset=Comment.objects.all().select_related('author').order_by('-created_at').only(*values['comment']),
          to_attr='comments'
          )
        )
      .prefetch_related(
        Prefetch(
          'likes',
          queryset=Like.objects.all().select_related('user').order_by('-created_at').only(*values['like']),
          to_attr='islike'
          )
      )
      .prefetch_related(
        Prefetch(
          'tags',
          queryset=Tag.objects.all(),
          to_attr='hasTags'
          )
      )
      .annotate(
        Count('comment'),
        Count('likes'),
      )
      .only(*values['origin'])
  )

  def get_queryset(self):
      return self.queryset

  def get_context_data(self, **kwargs):
    return super().get_context_data(**kwargs)

class ItemCreate(LoginRequiredMixin, CreateView):
  model = Item
  form_class = CreateItemForm
  template_name = 'item/create.html'

  def form_valid(self, form):
    item = form.save(commit=False)
    item.author = self.request.user
    item.save()
    if tags := self.request.POST['tags'].split(','):
      for tag_name in tags:
        tag_name = tag_name.strip()
        if tag_name != '':
          if exist := Tag.objects.filter(name=tag_name).first():
            item.tags.add(exist)
          else:
            item.tags.create(name=tag_name)

    return redirect('item.detail', pk=item.id)

class ItemDelete(LoginRequiredMixin, DeleteView):
  model = Item
  template_name = 'item/delete.html'
  success_url = reverse_lazy('item.list')

  def get_queryset(self):
    queryset = super().get_queryset()
    return queryset.filter(author=self.request.user)

class ItemUpdate(LoginRequiredMixin, UpdateView):
  model = Item
  form_class = CreateItemForm
  template_name = 'item/update.html'
  success_url = reverse_lazy('item.list')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    tags = self.object.tags.all()
    arr = [tag.name for tag in tags]
    context['tag_arr'] = arr
    return context

  def get_queryset(self):
    queryset = super().get_queryset()
    return queryset.filter(author=self.request.user)

  def form_valid(self, form):
    item = form.save(commit=False)
    item.save()

    # Remove current tags
    current_tags = item.tags.all()
    for current_tag in current_tags:
      item.tags.remove(current_tag)
      if current_tag.item_set.count() == 0:
        current_tag.delete()

    if tags := self.request.POST['tags'].split(','):
      for tag_name in tags:
        tag_name = tag_name.strip()
        if tag_name != '':
          if exist := Tag.objects.filter(name=tag_name).first():
            item.tags.add(exist)
          else:
            item.tags.create(name=tag_name)

    return redirect('item.detail', pk=item.id)

def create_comment(request, pk):

  if request.method == 'POST':
    item = Item.objects.get(pk=pk)
    comment = Comment(body=request.POST.get('comment'), author=request.user, item=item)
    comment.save()
    return redirect('item.detail', pk=pk)

def delete_item(request, pk):

  if request.method == 'POST':
    item = Item.objects.get(pk=pk)
    if item.author == request.user:
      item.delete()
      data = {"msg": 'ok'}
    else:
      data = {"msg": 'ng'}

  return JsonResponse(data)

def like(request, pk):
  if request.method == 'POST':
    item = Item.objects.get(pk=pk)
    like = item.likes.filter(user=request.user)
    if flg := like.exists():
      like.delete()
    else:
      l = Like(user=request.user, item=item)
      l.save()
      item.likes.add(l)
    cnt_all = item.likes.count()
    cnt_current = like.count()
    data = {
      "cntAll": cnt_all,
      "cntCurrent": cnt_current
      }
  else:
    data = { "msg": 'Bad method' }

  return JsonResponse(data)

class IndexView(ItemList):
  template_name = 'index.html'

  def get_queryset(self):
    return super().get_queryset()[:3]

index = IndexView.as_view()

class HomeView(ItemList):
  template_name = 'home.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    items = self.get_queryset()
    myitems = items.filter(author=self.request.user)
    context['myitems'] = myitems

    mylikes = items.filter(likes__user=self.request.user).order_by('-likes__created_at')
    context['mylikes'] = mylikes

    mycomments = Comment.objects.filter(author=self.request.user).select_related('author').order_by('-created_at')
    context['mycomments'] = mycomments

    try:
      hero = myitems.first()
      context['hero'] = hero.getThumbnailImage()
    except (Item.DoesNotExist, AttributeError):
      context['hero'] = f'{settings.STATIC_URL}img/bg-0.jpg'

    return context

class ItemTagList(ListView):
  template_name = 'item/tag_list.html'
  paginate_by = 6
  queryset = (
    Item.objects.all()
      .select_related('author')
      .prefetch_related(
        Prefetch(
          'comment_set',
          queryset=Comment.objects.all().select_related('author').order_by('-created_at'),
          to_attr='comments'
          )
        )
      .prefetch_related(
        Prefetch(
          'likes',
          queryset=Like.objects.all().select_related('user').order_by('-created_at'),
          to_attr='islike'
          )
      )
      .annotate(
        Count('comment'),
        Count('likes'),
      )
  )

  def get_queryset(self):
    q = self.queryset.filter(tags__id=self.kwargs['pk']).order_by('-created_at')
    if self.request.user.is_authenticated:
      q = q.annotate(currentuser_islike=Count('likes', filter=Q(likes__user=self.request.user)))
    if 'sort' in self.request.GET and self.request.GET.get('sort') != 'created_at':
      sort = self.request.GET.get('sort')
      try:
        q = q.annotate(sort=Count(sort)).order_by('-sort', '-created_at')
      except FieldError:
        q = q
    return q

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      tag_name = Tag.objects.get(pk=self.kwargs['pk'])
      context['tag_id'] = self.kwargs['pk']
      context['tag_name'] = tag_name
      return context

app/templates/item/create.html
{% extends '../base.html' %}

{% block head_title %}Item Create | {{ block.super }}{% endblock %}

{% block content %}
<div class="sm:w-2/3 max-w-5xl mx-auto">
  <div class="mx-4 sm:mx-0 my-4 sm:my-8">
    <div>
      <h1 class="text-2xl font-bold">Post an item</h1>
      <div class="bg-white p-4 sm:p-8 my-8 shadow-sm w-full">
        <form class="w-full" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div>
            <label class="block mb-2 text-sm" for="id_title">title</label>
            <input class="input" type="text" name="title" required="" id="id_title">
          </div>
          <div>
            <label class="block mb-2 text-sm" for="id_body">this paper</label>
            <textarea class="input" name="body" cols="40" rows="5" required="" id="id_body"></textarea>
          </div>
          <div class="mb-4">
            <label class="block mb-2 text-sm" for="id_tags">タグ</label>
            <input type="text" name="tags" id="id_tags">
          </div>
          <div class="flex mb-4">
            <div>
              <label class="block mb-2 text-sm" for="id_image">image</label>
              <input class="" type="file" name="image" accept="image/*" id="id_image">
            </div>
            <div>
              <img id="img-preview" class="w-full object-cover">
            </div>
          </div>
          <div class="text-center mt-8">
            <button class="btn btn-black btn-wide" type="submit">Post</button>
          </div>
        </form>
      </div>

      <a class="btn btn-gray" href="{% url 'item.list' %}">cancel</a>
    </div>
  </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
  libs.setPreview('input[name="image"]', '#img-preview')
  libs.setTags('#id_tags')

</script>
{% endblock %}

app/templates/item/delete.html
{% extends '../base.html' %}

{% block head_title %}{{ object.title }} | {{ block.super }}{% endblock %}

{% block content %}
<h1>Delete item</h1>
<form action="" method="POST">
  {% csrf_token %}
  <div>
    <button type="submit">send</button>
  </div>
</form>
{% endblock %}

app/templates/item/detail.html
{% extends '../base.html' %}

{% load static %}

{% block head_title %}{{ object.title }} | {{ block.super }}{% endblock %}

{% block content %}
<div class="max-w-5xl mx-4 sm:mx-auto my-8">
  <h1 class="text-2xl font-bold mb-4">{{ object.title }}</h1>
  <div class="flex items-center justify-between mb-4">
    <div class="flex items-center">
      <img class="w-8 h-8 object-cover rounded-full mr-2" src="{{ object.author.getAvatar }}" alt="{{ object.author.username }}">
      <div>
        <p class="mb-1">{{ object.author.username }}</p>
        <div class="flex">
          <i class="fas fa-calendar-alt text-gray-400 text-xs mr-1"></i>
          <span class="text-gray-400 text-xs">{{ object.created_at|date:"Y/m/j" }}</span>
        </div>
      </div>
    </div>
    {% if object.hasTags is not None %}
    <div class="flex">
      {% for t in object.hasTags %}
      <span class="bg-gray-200 rounded-sm ml-2"><a class="block text-xs px-4 py-2" href="{% url 'item.tag_list' t.id %}">{{ t.name }}</a></span>
      {% endfor %}
    </div>
    {% endif %}
  </div>
  <div class="shadow-sm">
    <div>
      <img src="{{ object.getThumbnailImage }}" alt="{{ object.title }}">
    </div>
    <div class="p-8 mb-4 bg-white">
      <p>{{ object.body }}</p>
    </div>
  </div>
  {% if user.id == object.author.id %}
  <div class="flex justify-end">
    <div class="flex text-blue-500">
      <div class="flex mr-4 select-none">
        <i class="fas fa-pencil-alt mr-1"></i>
        <a class="" href="{% url 'item.update' object.pk %}">edit</a>
      </div>
      <div class="flex select-none">
        <i class="fas fa-trash-alt mr-1"></i>
        <button id="btn-del" class="" href="">delete</button>
      </div>
    </div>
  </div>
  {% endif %}
  <div class="flex items-center justify-between">
    <h3 class="text-xl my-4 font-bold">comment</h3>
    <a class="text-gray-400 text-sm" href="#comment-area">Write a comment</a>
  </div>
  {% if object.comment__count > 0 %}
  <div class="grid grid-cols-1 gap-y-4">
    {% for c in object.comments %}
    {% include '../components/_comment.html' %}
    {% endfor %}
  </div>
  {% else %}
  <p>No comments</p>
  {% endif %}
  <a class="btn btn-gray my-4" href="{% url 'item.list' %}">Return</a>
  <h3 id="comment-area" class="text-xl my-4 font-bold">Write a comment</h3>
  <div>
    <form action="{% url 'item.create_comment' object.id %}" method="POST">
      {% csrf_token %}
      <textarea name="comment" id="" cols="50" rows="5" class="input"></textarea>
      <div class="text-center">
        <button type="submit" class="btn btn-black btn-wide">transmission</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
  fetchItem.del('{{ object.id }}')

</script>
{% endblock %}

app/templates/item/list.html
{% extends '../base.html' %}

{% load static %}

{% block head_title %}Item List | {{ block.super }}{% endblock %}

{% block extracss %}
{% endblock %}

{% block content %}
<div class="container mx-2 sm:mx-4 my-8 lg:max-w-5xl">
  <div class="mx-2 sm:mx-0 my-4 sm:my-4 flex items-center justify-between">
    <h1 class="text-xl sm:text-2xl font-bold">item</h1>
    <div class="flex items-center">
      <select name="sort" id="sort" class="w-32 input mb-0 mr-4 cursor-pointer">
        <option value="created_at">Order of most recent</option>
        <option value="likes">Like order</option>
        <option value="comment">Comment order</option>
      </select>
      <a class="btn btn-black" href="{% url 'item.create' %}">Post</a>
    </div>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 mx-2 sm:mx-auto">
    {% for item in object_list %}
    {% include '../components/_card.html' %}
    {% endfor %}
  </div>
  {% include '../components/_paginate.html' %}
</div>
{% endblock %}

{% block extrajs %}
<script>
  fetchItem.like()
  fetchItem.sort('#sort')

</script>
{% endblock %}

app/templates/item/tag_list.html
{% extends '../base.html' %}

{% load static %}

{% block head_title %}Tag List | {{ block.super }}{% endblock %}

{% block extracss %}
{% endblock %}

{% block content %}
<div class="container mx-2 sm:mx-4 my-8 lg:max-w-5xl">
  <div class="mx-2 sm:mx-0 my-4 sm:my-4 flex items-center justify-between">
    <h1 class="text-xl sm:text-2xl font-bold">{{ tag_name }}</h1>
    <div class="flex items-center">
      <select name="sort" id="sort" class="w-32 input mb-0 mr-4 cursor-pointer">
        <option value="created_at">Order of most recent</option>
        <option value="likes">Like order</option>
        <option value="comment">Comment order</option>
      </select>
      <a class="btn btn-black" href="{% url 'item.create' %}">Post</a>
    </div>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 mx-2 sm:mx-auto">
    {% for item in object_list %}
    {% include '../components/_card.html' %}
    {% endfor %}
  </div>
  {% include '../components/_paginate.html' %}
</div>
{% endblock %}

{% block extrajs %}
<script>
  fetchItem.like()
  fetchItem.sort('#sort', '{{ tag_id }}')

</script>
{% endblock %}

app/templates/item/update.html
{% extends '../base.html' %}

{% block head_title %}{{ object.title }} | {{ block.super }}{% endblock %}

{% block content %}
<div class="container my-8 sm:mx-auto sm:w-2/3 max-w-5xl">
  <div class="mx-4">
    <h1 class="text-2xl font-bold">Edit an item</h1>
    <div class="bg-white p-4 sm:p-8 my-8 shadow-sm w-full">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
          <label class="block mb-2 text-sm" for="id_title">title</label>
          <input class="input" type="text" name="title" required="" id="id_title" value="{{ object.title }}">
        </div>
        <div>
          <label class="block mb-2 text-sm" for="id_body">this paper</label>
          <textarea class="input" name="body" cols="40" rows="5" required="" id="id_body">{{ object.body }}</textarea>
        </div>
        <div class="mb-4">
          <label class="block mb-2 text-sm" for="id_tags">tag</label>
          <input type="text" name="tags" id="id_tags">
        </div>
        <div class="flex mb-4">
          <div>
            <label class="block mb-2 text-sm" for="id_image">image</label>
            <input class="" type="file" name="image" accept="image/*" id="id_image">
          </div>
          <div>
            <div id="img-preview">
              {% if object.image %}
              <img id="img-tag" class="w-full object-cover" src="{{ object.image_thumbnail.url }}" alt="">
              {% else %}
              <img id="img-tag" class="w-full object-cover">
              {% endif %}
            </div>
          </div>
        </div>
        <div class="text-center mt-8">
          <button class="btn btn-black btn-wide" type="submit">update</button>
        </div>
      </form>
    </div>
    <a class="btn btn-gray" href="{% url 'item.detail' item.id %}">cancel</a>
  </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
  libs.setPreview('input[name="image"]', '#img-tag')
  libs.setTags('#id_tags', '{{tag_arr}}')

</script>
{% endblock %}